### PR TITLE
Added Malay language support (ms_MS)

### PR DESCRIPTION
**Pull request by SentulAsia**
A simple Malay language translations

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks - will look soon.

**Comment by SentulAsia** [comment]
@ArtSabintsev wondering when will this pull will appear in next cocoa pods? looking to use the translations in 2 weeks time...

**Comment by ArtSabintsev** [comment]
Whoops - I forgot. Will do it tonight after work.

**Comment by ArtSabintsev** [comment]
Just pushed v0.6.1. 

Thanks for your help! I'll be adding this to Harpy shortly.

**Pull request merged**
