### PR TITLE
Adds updateAlertType support for apps using only major and minor numb…

### PR DESCRIPTION
**Pull request by liebeskind**
…ering system

### CODE REVIEW

**Comment by getaaron** [comment]
I think an approach like this would be simpler:

```swift
if 2...3 ~= oldVersion.count && oldVersion.count == newVersion.count {
    if newVersion[0] > oldVersion[0] { // A.b[.c]
        alertType = majorUpdateAlertType
    } else if newVersion[1] > oldVersion[1] { // a.B[.c]
        alertType = minorUpdateAlertType
    } else if newVersion.count == 3 && newVersion[2] > oldVersion[2] { // a.b.C
        alertType = patchUpdateAlertType
    }
}
```

**Comment by ArtSabintsev** [comment]
Agreed. We should extend it to 4 as well, as ice seen many projects use that system as well. Want to add the code and push it live on here and cocoapods, Aaron?

**Comment by getaaron** [comment]
I can get to it tonight unless @liebeskind wants to do it.

**Comment by ArtSabintsev** [comment]
Ok np - I may have time tonight as well - depends on go fast I get to my destination right now :) make a post here if you start working in it, so no one else does double work.

Thanks!

**Comment by liebeskind** [comment]
Thanks for the feedback guys.  I'll implement your suggestions now and re-pull.

DL

**Comment by ArtSabintsev** [comment]
Sounds go, @liebeskind! If you can make it handle from 2-4 numbers, that would be awesome.

**Comment by liebeskind** [comment]
Should be good to go

**Comment by ArtSabintsev** [comment]
This looks great! Thanks! I'll accept the PR momentarily.

**Comment by ArtSabintsev** [comment]
ok, v0.4.1 is live. Changes to README and CONTRIBUTORS.md were also made.

Thanks again guys!

**Comment by getaaron** [comment]
Thanks for the PR, @liebeskind.

**Pull request merged**
