### PR TITLE
HTTPS when supported

### PR DESCRIPTION
**Pull request by Coeur**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks, but you edited the automatically generated docs. Many of those changes will be reverted when I re-run Jazzy, the docs generating tool.

**Comment by Coeur** [comment]
@ArtSabintsev I can redo the commit you know. :)

**Comment by Coeur** [comment]
@ArtSabintsev  I've redone the commit, you may re-open the pull request.

**Comment by ArtSabintsev** [comment]
You have to resubmit the PR.

**Pull request closed without merging**
