### PR TITLE
Added wail with provided newer version

### PR DESCRIPTION
**Pull request by tateviktome**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
hey, thanks for the PR. 

Is this to do some local client-side testing?

**Comment by tateviktome** [comment]
> hey, thanks for the PR.
> 
> Is this to do some local client-side testing?

Thanks for quick reply! Yes, this is to do local client-side testing.

**Comment by ArtSabintsev** [comment]
Still thinking about this PR. Why would you want to do this exactly? You can simply change the project version and you get the same effect.

This code is for debugging only, which is why I'm hesitant to update the library with this change.

**Comment by tateviktome** [comment]
I am still ok if You don't update cause I have the appropriate changes in my forked repository. So yes, if You find unnecessary, then it's ok 🙂.

**Comment by ArtSabintsev** [comment]
ok, thanks. I appreciate the effort here, but I think it's beyond the scope of this repository. I'm going to close the PR without merging.

Thanks!

**Pull request closed without merging**
