### PR TITLE
Add translations in Greek (el), Finnish (fi), and Indonesian (id)

### PR DESCRIPTION
**Pull request by ChrisixFlash**
In this branch we added translations for  the update alert function for the Viewer app in the languages el, fi, and id.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Seems to be a merge conflict with the Greek translation, as I added a Greek translation last week.

**Comment by ArtSabintsev** [comment]
Also, can you add the appropriate tests for the Finnish and Indonesian languages?

**Comment by ChrisixFlash** [comment]
@ArtSabintsev Oh I'm very sorry, I'll delete the Greek one then.

**Comment by ArtSabintsev** [comment]
Everything looks good. I'll merge this in soon.

**Comment by ChrisixFlash** [comment]
Great! 🙂

**Comment by ArtSabintsev** [comment]
Now available via CocoaPods as v1.1.1.

Thanks again, @ChrisixFlash! Your name was also added to the [CONTRIBUTORS.md](https://github.com/ArtSabintsev/Siren/blob/master/CONTRIBUTORS.md) file

**Comment by ChrisixFlash** [comment]
@ArtSabintsev Thank you, I was very glad I could help!

**Comment by ArtSabintsev** [comment]
Me too!

**Pull request merged**
