### PR TITLE
Swift2.3

### PR DESCRIPTION
**Pull request by arlo-egg**
Updates the project file and single minor syntax change to support swift 2.3

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
I'll make a separate branch and change the syntax for 2.3 in there. This will be later tonight.

Thanks for the PR.

**Comment by arlo-egg** [comment]
👍 I expected you would want to.

Is there a way to make a PR to a branch which doesn't currently exist? I do not know how.

**Comment by ArtSabintsev** [comment]
Nope, there isn't, but I'll give you credit for the initiative!

**Comment by ArtSabintsev** [comment]
Sorry, got stuck on a different task. I'll make the update this evening.

Arthur

**Comment by ArtSabintsev** [comment]
About to push the branch - closing this PR.

**Comment by ArtSabintsev** [comment]
Here you go: https://github.com/ArtSabintsev/Siren/pull/81

Check the README for CocoaPods/Carthage installation guides.

Thanks!

**Pull request closed without merging**
