### PR TITLE
Siren 1.0.0 WIP (Swift 3 Support)

### PR DESCRIPTION
**Pull request by ArtSabintsev**
I converted Siren to Swift 3 using the Xcode 8.0b2 migrator. 

This PR will be worked on and edited until Xcode 8.0 GM is released. At that point in time, Siren 1.0.0 will be released with full support for Swift 3. 

cc @getaaron for your input at your leisure.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
I will be making some syntactical changes shortly involving the exposing of labels for the first parameter in functions, in accordance of the new Swift design guidelines.

**Comment by ArtSabintsev** [comment]
This works with Xcode 8.0b3.

**Comment by ArtSabintsev** [comment]
I've merged it with Master, so it now works with the latest release (0.9.4).

**Comment by ArtSabintsev** [comment]
Added support with Xcode8b4.

**Comment by Tulleb** [comment]
Thanks a lot for your work @ArtSabintsev.
New issues just appeared with the released of Xcode8b6 yesterday.

Feel free to ask if you need any help with this?

**Comment by ArtSabintsev** [comment]
oh, jeez, 6 is out already, isn't it? I'll get to it tonight.

**Comment by ArtSabintsev** [comment]
Merging this branch into Master! 1.0.0 here we come!

**Pull request merged**
