### PR TITLE
Added Armenian language support (hy)

### PR DESCRIPTION
**Pull request by VahanMargaryan**
Added Armenian language support (hy)

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks - will add it today.

**Comment by ArtSabintsev** [comment]
Sorry, this slipped my mind. Will do it tonight. It's on my to-do list :)

**Comment by VahanMargaryan** [comment]
ok thanks ))

**Comment by ArtSabintsev** [comment]
Added too both Siren and [Harpy](http://github.com/artsabitnsev/harpy). Your name has been added to both contributors' documents as well.

Thanks, Vahan!

**Pull request merged**
