### PR TITLE
Fixes crash with nil iTunesURL

### PR DESCRIPTION
**Pull request by diamondsky**
Optional variable appID was unwrapped to `"https://itunes.apple.com/app/Optional..."`

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Hey, thanks for the PR!

Quick question, how did you get this to happen? THere's a measure in place that stops Siren from progressing to the alert if the appID isn't set.

**Comment by getaaron** [comment]
I think we just need to change `appID` to `appID!`, like in `iTunesURLFromString()`.

**Comment by ArtSabintsev** [comment]
Go ahead and test it out. If that fixes all the issues, feel free to submit and update the repo, etc. 

:)

**Comment by diamondsky** [comment]
@getaaron indeed, fixes the problem

**Comment by getaaron** [comment]
Thanks for updating, @diamondsky.

**Comment by ArtSabintsev** [comment]
@getaaron Will you take care of tagging/cocoapods, or do you want me to do that?

**Comment by getaaron** [comment]
@ArtSabintsev I'll do it.

**Comment by ArtSabintsev** [comment]
Thanks @getaaron!

Also, thank you @diamondsky for bringing the issue to oru attention. I'll add your name to the Contributors file in a short bit.

**Comment by ArtSabintsev** [comment]
ok, done. Credit has been given in both the README and CONTRIBUTORS files.

**Pull request merged**
