### PR TITLE
Siren 4.0.0

### PR DESCRIPTION
**Pull request by ArtSabintsev**
This PR will usher in a head-to-tail rewrite of Siren. Specifically, the following will occur:

- [x] Interface rewrite
- [x] Move core logic from `Siren.swift` to configurable managers 
- [x] Scope more data structures under `Siren`.
- [x] Implement #237 and #190 
- [x] Add Documentation
- [x] Update README

This PR is a WIP.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
@getaaron you may to take a look. This is a 100% rewrite sometime in the next week. Documentation is about 85% done and the readme nor sample project isn't in place at all, so it may be difficult to follow until then.

**Comment by ArtSabintsev** [comment]
@kamrankhan07 @jeffjvick @faasko - sorry if I'm pinging a couple of you out of the blue, but each of you have expressed an issue on SIren's ability for granular version updating in the last year.

This PR adds that functionality, on top of a full rewrite. It is ready to be tested.

Here’s the updated README: https://github.com/ArtSabintsev/Siren/blob/d78c2b427726b0f478126bc498718ff03456ef2d/README.md

Here’s a bunch of sample ways to implement Siren (AppDelegate.swift):
https://github.com/ArtSabintsev/Siren/blob/d78c2b427726b0f478126bc498718ff03456ef2d/Example/Example/AppDelegate.swift

**Comment by kamrankhan07** [comment]
Thanks a lot. I will check it out in couple of days. I appreciate all the effort you put into it 👍

**Comment by ArtSabintsev** [comment]
Great - thank you! My hope is to merge this in very soon - so if you have time to test it very quickly in the next 24 hours, I’d appreciate it!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jeffjvick** [comment]
Hi, good timing.  I was about to add Harpy to a new project I'm working
on.  I will see if I have time to test it today.

**Comment by ArtSabintsev** [comment]
@jeffjvick Thanks so much! I look forward to hearing back!

**Comment by ArtSabintsev** [comment]
Merging this code as I've received enough feedback that it seems to work. 👍

**Comment by jeffjvick** [comment]
Thanks. Sorry I was busy all day with a backend issue. I should get to integration in a day or two.

Sounds like it’s working but I can give it a double check with the feature I was looking for.

**Comment by ArtSabintsev** [comment]
No worries and thanks for following up! It was me that was in a rush, as I was excited to close this PR. Keep me posted!

**Comment by kamrankhan07** [comment]
@ArtSabintsev I have started testing it now, looks great. I saw one issue/suggestion, if the alert if presented then the completion handler is not called to let user know that an alert is being shown on screen right now. We used to have sirenDidShowUpdateDialog in the previous code.

**Comment by ArtSabintsev** [comment]
Right, the completion handler is only called upon the user performing an action on the modal, otherwise, there is no reason to call the completion handler. Is this an issue?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kamrankhan07** [comment]
I have a scenario, and may be some other people will have to, where I need to know if the alert was presented. I thought more about it and I can change my code to adapt. If you think it will be good idea to have some way of getting to know if alert was presented or if its a useful information then it can be added.

**Comment by ArtSabintsev** [comment]
You will find out if the alert is presented once they interact with it. I could add a notification the scenario when the alert is presented and they background the app - that could potentially cause the completion handler to get called, however, it may cause the app not to update depending on the prompt rules. Does that work?

Why do you need to know if the alert was presented? What metrics do you get from that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kamrankhan07** [comment]
I have some scenario in app where we show user some banners which have some constraints on them i.e. they will not appear again once shown to user. If app update notification shows (which can be force update too), those banners will disappear without any user interaction. So, for my test case, I just check if there is any update available or not before deciding to call our server to get banner data. But may be people will have other scenarios where they want to know. 
I checked your code and in most cases I will get the callback if there is no update available, except the case where alert is shown. I have a work around for my scenario. May be we can wait and see if other people need such a thing and for whatever test case that they have and then a good approach can be selected for it.

**Comment by kamrankhan07** [comment]
I liked the the changes you made in code, really excellent work.

**Comment by kamrankhan07** [comment]
@ArtSabintsev I saw one more issue, if an alert is present on the screen and app is minimized and launched again then it will show another alert on top of that because of performVersionCheck() called via the observer UIApplication.didBecomeActiveNotification. Its easy to test with promptFrequency =  .immediately

**Comment by kamrankhan07** [comment]
updaterWindow is reinitialized every time its referenced. Possible fix
```
 private var updaterWindow: UIWindow = {
        let window = UIWindow(frame: UIScreen.main.bounds)
        window.rootViewController = SirenViewController()
        window.windowLevel = UIWindow.Level.alert + 1
        return window
    }()
```

**Comment by ArtSabintsev** [comment]
Thanks - are you able to post your appdelegate’s implementation of Siren? I just want to see how you’re using it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kamrankhan07** [comment]
If user is not logged in then the implementation is simple, I call Siren once from didFinishLaunchingWithOptions. I have a helper class where code looks like this

```
func checkVersion(_ completion:((_ redirected: Bool) -> ())?) {
        self.versionNumberOnServer { versionOnServer in
            if self.shouldForceUser(versionOnServer) {
                Siren.shared.rulesManager = RulesManager(globalRules: .critical,
                                                         showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
            } else {
                Siren.shared.rulesManager = RulesManager(globalRules: Rules(promptFrequency: .daily, forAlertType: .skip),
                                                         showAlertAfterCurrentVersionHasBeenReleasedForDays: 0)
            }
            
            Siren.shared.wail { (results, error) in
                if let results = results {
                    if results.alertAction == .appStore {
                        completion?(true)
                    } else {
                        completion?(false)
                    }
                } else if let error = error {
                    print(error.localizedDescription)
                    completion?(false)
                }
            }
        }
    }
```

**Comment by ArtSabintsev** [comment]
And if the user _is_ logged in? Are you still only calling your code in `didFinishLaunching WithOptions`? My worry is that you should not seeing this behavior: https://github.com/ArtSabintsev/Siren/pull/250#issuecomment-451368285

**Comment by kamrankhan07** [comment]
If logged in then I have a different flow. I debugged both ways and issue seemed to be with that code, after I made those changes everything was working fine. I can check it again tomorrow. You can not reproduce the behaviour ?

**Comment by ArtSabintsev** [comment]
Alright, I was able to emulate that layered pop-up alert. Working on a fix.

**Comment by ArtSabintsev** [comment]
Alright, fixed it in https://github.com/ArtSabintsev/Siren/releases/tag/4.0.1. 

Thanks for the bug report. 

I'm locking this PR from further comments, but feel free to open a new issue if this problem or any other problem persists.

**Pull request merged**
