### PR TITLE
Swift 5 Implementation and Architecture Changes

### PR DESCRIPTION
**Pull request by ArtSabintsev**
- Adds Swift 5 Support (#279) 
- Implementes Swift 5's `Result` type in `Siren.swift` and `APIManager.swift`
- Renames `LookupModel.swift` to `APIModel.swift`.
- Exposes all values in `APIModel.swift` in a nice public API on a new struct, `Model.swift`. (#276)
- Siren's public completion handler now uses the `Result` type and returns `Model.swift` instead of `APIModel.swift`.
- Fixes the placement of the `Update` button on `.optional` alerts (#278)

### CODE REVIEW

**Comment by HarryPT** [comment]
Thank you.

**Comment by ArtSabintsev** [comment]
You're welcome! I'm still working on a few small things, but hoping to merge and release this today.

**Comment by ArtSabintsev** [comment]
Implemented in https://github.com/ArtSabintsev/Siren/pull/279.

**Comment by emanharout** [comment]
Thanks for the quick fix on the update button!

**Pull request merged**
