### PR TITLE
WIP: Update ja localization

### PR DESCRIPTION
**Pull request by nixnoughtnothing**
As a native speaker of Japanese, the previous one sounds a little bit weird (it's ok but can be improved). So I fixed to make it sound more natural : D

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Mind making the same change to Harpy?

**Comment by nixnoughtnothing** [comment]
>Mind making the same change to Harpy?

Sure thing!

**Comment by ArtSabintsev** [comment]
Thanks! Pushed out v2.0.8 with your changes! Thanks again!

**Comment by nixnoughtnothing** [comment]
Thanks for merging it! Fixed harpy as well. https://github.com/ArtSabintsev/Harpy/pull/177

**Comment by ArtSabintsev** [comment]
Great - thank you. Just having the CI run on Harpy now before merging.

**Comment by nixnoughtnothing** [comment]
Thanks again!

  
LGTM

**Pull request merged**
