### PR TITLE
Fixes #89

### LINKED ISSUE #89: Update Latvian translation
Latvian translation is wrong. Need to update from official term guidelines: http://termini.lza.lv/

### PR DESCRIPTION
**Pull request by fassko**
Update Latvian translations

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
So, you're saying there are new _official_ terms for certain technical words in the Latvian language, and they are listed at http://termini.lza.lv/?

**Comment by fassko** [comment]
Translations aren't correct. I'm Latvian, so no worries. :)

**Comment by ArtSabintsev** [comment]
ok - thanks. I'll update it tonight on this project and on Harpy.

**Comment by ArtSabintsev** [comment]
I haven't forgotten about this stuff - I'll do it tomorrow.

**Comment by ArtSabintsev** [comment]
Can you also modify the test in the testing bundle?

**Comment by ArtSabintsev** [comment]
I'll do it myself right now.

**Comment by ArtSabintsev** [comment]
ok, fixed the tests - it's available as version 1.0.2 in all the package managers. Will add the same fix to [Harpy](http://github.com/ArtSabintsev/Harpy).

**Pull request merged**
