### PR TITLE
translate README.md into Chinese

### PR DESCRIPTION
**Pull request by zongmumask**
translate README.md into Chinese so that more developer from China could benefit from this repo

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
@zongmumask Thank you for doing this!

Would you be willing to update the README whenever I make big changes to the English README?

**Comment by zongmumask** [comment]
I'd love to.I will update the README file whenever you make any big changes to the English README.You can send me an email when you update the English README.

**Comment by ArtSabintsev** [comment]
Sounds good. I will do that!

Make sure to give yourself credit for the translation at the bottom of the README, and I will merge it in afterwards

Thank you!.

**Comment by zongmumask** [comment]
Thank you! I add a `Translated by` section at the bottom of both README and README.zh_CN

**Comment by ArtSabintsev** [comment]
Sounds good! Merging it in now.

**Pull request merged**
