### PR TITLE
Add skipOption to AlertType

### PR DESCRIPTION
**Pull request by kalupas226**
Nice to meet you!
Thank you for letting us use your wonderful library!

Today, I want to use AlertController with only skip and update action.
So I send you a pull request.

If you have free time, please check my pull request?

### CODE REVIEW

**Comment by kalupas226** [comment]
And sorry, I tried to edit html docs.
But I wasn't sure where to edit, so I decided to ask your opinion.
Best regards.

**Comment by ArtSabintsev** [comment]
Hi,

Thanks for the PR!

The HTML docs are automatically generated using `jazzy`. So in 8 years of managing Harpy and Siren, no one has ever asked for this feature. What's the use case here?

Thanks!

**Comment by kalupas226** [comment]
@ArtSabintsev 
Thanks for your reply!

> The HTML docs are automatically generated using jazzy. 

I see. Thank you.

>  no one has ever asked for this feature

AlertType.option has two alerts: nextTimeAlertAction and updateAlertAction. 
NextTimeAction will alert you again after the next launch. 
However, I found that to be a bit noisy for some people. 
Also, AlertType.skip has three actions. 
However, I found the number of actions to be redundant for the situations I wanted to use it for. 
Also, I wanted to keep the number of buttons in the Alert to two in accordance with the [Human Interface Guideline](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/), even though there are three buttons displayed in the Alert.

So, I thought I want to use two button alert has skip and update button.

Thanks!

**Comment by ArtSabintsev** [comment]
Hey, I thought this over. While I am principally not against it, I don't think it's necessary. This is the first time in 8 years I have received this request, which to me, means that it's a feature for the minority of users (and/or developers), and if anything, adds to the complexity of configuration of Siren by adding a feature that will be used by a minority of folks (if they even discover it). 

While a 3 button `UIAlertController` may not align with the HIG, it's still allowed by virtue of the UI being able to support it. Also, Apple has introduced their own AlertController's with [3 interaction points](https://2672686a4cf38e8c2458-2712e00ea34e3076747650c92426bbb5.ssl.cf1.rackcdn.com/2017-03-21-10-18-38.jpeg), so they're not following their own suggested rules to some extent.

While I appreciate the sentiment here, and that you care about _noisiness_ for some people, as you called it, I don't see that  as being worthwhile enough to add to the library. I tend to write code for the majority of use cases, not the minority, especially when vendoring an open source library. 

For all the reasons above, I will be delcining this PR. You are welcome to use it on your own fork for your own needs, especially as Siren is in a very stable state these days, so there shouldn't be too many times where you'd need to sync with master.

Thanks for understanding!

**Comment by kalupas226** [comment]
@ArtSabintsev 

Thanks for taking the time to think about it.
And thank you for your careful explanation, I was able to agree with your opinion.

I certainly think Siren is so stable that I decided to either rethink the design of the app or fork Siren over to use it.

Thank you!!

**Comment by ArtSabintsev** [comment]
Awesome - happy to hear it. I'll be locking this thread now

**Pull request closed without merging**
