### PR TITLE
feat: added cache busting parameter to itunes request url

### PR DESCRIPTION
**Pull request by bbialas**
Fix for the issue reported here:
https://github.com/ArtSabintsev/Siren/issues/413

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks - I'll test it in the next week or so.

**Comment by ArtSabintsev** [comment]
hi, do you have documentation on the `t` parameter being a valid parameter on the `lookup` API? 

Thanks!

**Comment by bbialas** [comment]
Hi,
no, there is no official documentation on that, but there is also no documentation on what kind of cache they apply to the request.

Looks like they do not block any extra params, and timestamp in URL is a pretty common cache-busting technique.

**Comment by ArtSabintsev** [comment]
right, but there's no way to prove this is actually a solution.

**Comment by bbialas** [comment]
Hey, so what do we do with this change?

**Comment by ArtSabintsev** [comment]
I don't believe there's a path forward because there is no way to prove that this actually works. I think I'm going to close this pool request, and you can use this on your own branch.

**Pull request closed without merging**
