### PR TITLE
support OS X

### PR DESCRIPTION
**Pull request by wud147**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Thanks for this PR. I won't have a chance to really test it out for another 7-10 days because of other obligations I have, plus my limited experience with mac dev.

**Comment by wud147** [comment]
@ArtSabintsev I'll add sample app and test case in the next few days, but I'm a little confused which directory should I put it in , as lots of tests will be the same as the iOS, so i suggest adjust the structure of directory as follows:
|root
  - iOS Sample App
  - OSX Sample APP
  - Siren
  - SirenTests
  - other config files

how about it ?

**Comment by ArtSabintsev** [comment]
Host the same app yourself and send me a link in this PR. It'll be enough for me to perform the test. As for tests, no news ones are needed, as I only test localization and version upgrade code paths.

I'll add a Sample App later, after playing with yours.

**Comment by wud147** [comment]
@ArtSabintsev  Here is the sample app , just copy some code from iOS Sample. 
https://github.com/wud147/Siren-OSX-Sample
any question , just leave message in here.^_^

**Comment by ArtSabintsev** [comment]
Sorry for the delay. Will be looking at this on Thursday.

**Comment by ArtSabintsev** [comment]
I's been about 3 months since we spoke on this subject. Since then, not one person has asked for this feature, and since then, the Mac App Store has more-or-less ceased functioning for me. I'm making the executive decision that I will not be supporting the Mac App Store as I just don't want to deal with it. 

Thank you for your effort, but I will not be adding this feature.

**Pull request closed without merging**
