### PR TITLE
review zh-Hans, zh-Hant i18n strings.

### PR DESCRIPTION
**Pull request by ToroLiu**
Make words more in line with Chinese usage.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Hi - thanks for the PR! 

Which strings did you update in each file? It's hard to tell as this is these are binary files in GitHub's eyes.

**Comment by ArtSabintsev** [comment]
Closing this issue due to lack of follow up.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ToroLiu** [comment]
I update following string files.

Sources/Siren.bundle/zh-Hans.lproj/SirenLocalizable.strings
Sources/Siren.bundle/zh-Hant.lproj/SirenLocalizable.strings

I open them by sublime text editor. They are plain text string files.

**Comment by ArtSabintsev** [comment]
Right, but which specific strings in there did you change? There are five strings in each one. I need to do a secondary verification and potentially update tests.

**Pull request closed without merging**
